// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCiABqWhJzlukSbbCQ5wckMYEfoFq6wBs',
    appId: '1:285656052775:android:aca5c1857d249880f80a02',
    messagingSenderId: '285656052775',
    projectId: 'gooday-app',
    storageBucket: 'gooday-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcdeHaCMWaeCCazgV0-Uk-0dF9cVF8WX4',
    appId: '1:285656052775:ios:9581faef920f81a2f80a02',
    messagingSenderId: '285656052775',
    projectId: 'gooday-app',
    storageBucket: 'gooday-app.appspot.com',
    androidClientId:
        '285656052775-0bkcad381r1bgcaobau009hdes230lnd.apps.googleusercontent.com',
    iosClientId:
        '285656052775-0u4vhcena0mbrmmq15buvknt29piikt2.apps.googleusercontent.com',
    iosBundleId: 'care.gooday.app',
  );
}
